services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: collabhub_user
      POSTGRES_PASSWORD: votre_mot_de_passe
      POSTGRES_DB: collabhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: